---
version: '3'

services:
  yb-master-n1:
    image: yugabytedb/yugabyte:latest
    hostname: yb-master-n1
    container_name: yb-master-n1
    privileged: true 
    ports:
      - 7001:7000  
    entrypoint: ['/home/yugabyte/bin/yb-master', '--replication_factor=1', '--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100', '--rpc_bind_addresses=yb-master-n1:7100', '--enable_ysql=true', '--fs_data_dirs=/mnt/disk0,/mnt/disk1', '--yb_num_shards_per_tserver=2', '--ysql_num_shards_per_tserver=2', '--v=0']

  yb-master-n2:
    image: yugabytedb/yugabyte:latest
    hostname: yb-master-n2
    container_name: yb-master-n2
    privileged: true 
    ports:
      - 7002:7000  
    entrypoint: ['/home/yugabyte/bin/yb-master', '--replication_factor=1', '--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100', '--rpc_bind_addresses=yb-master-n2:7100', '--enable_ysql=true', '--fs_data_dirs=/mnt/disk0,/mnt/disk1', '--yb_num_shards_per_tserver=2', '--ysql_num_shards_per_tserver=2', '--v=0']
      
  yb-master-n3:
    image: yugabytedb/yugabyte:latest
    hostname: yb-master-n3
    container_name: yb-master-n3
    privileged: true 
    ports:
      - 7003:7000  
    entrypoint: ['/home/yugabyte/bin/yb-master', '--replication_factor=1', '--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100', '--rpc_bind_addresses=yb-master-n3:7100', '--enable_ysql=true', '--fs_data_dirs=/mnt/disk0,/mnt/disk1', '--yb_num_shards_per_tserver=2', '--ysql_num_shards_per_tserver=2', '--v=0']

  yb-tserver-n1:
    image: yugabytedb/yugabyte:latest
    hostname: yb-tserver-n1
    container_name: yb-tserver-n1
    privileged: true
    ports:
      - 9001:9000 
      - 9042:9042
      - 5433:5433
    entrypoint: ['/home/yugabyte/bin/yb-tserver', '--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100', '--rpc_bind_addresses=yb-tserver-n1:9100', '--memory_limit_hard_bytes=1073741824', '--use_cassandra_authentication=false', '--enable_ysql=true', '--pgsql_proxy_bind_address', 'yb-tserver-n1:5433', '--fs_data_dirs=/mnt/disk0,/mnt/disk1', '--yb_num_shards_per_tserver=2', '--ysql_num_shards_per_tserver=2', '--v=0']

  yb-tserver-n2:
    image: yugabytedb/yugabyte:latest
    hostname: yb-tserver-n2
    container_name: yb-tserver-n2
    privileged: true
    ports:
      - 9002:9000 
    entrypoint: ['/home/yugabyte/bin/yb-tserver', '--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100', '--rpc_bind_addresses=yb-tserver-n2:9100', '--memory_limit_hard_bytes=1073741824', '--use_cassandra_authentication=false', '--enable_ysql=true', '--pgsql_proxy_bind_address', 'yb-tserver-n2:5433', '--fs_data_dirs=/mnt/disk0,/mnt/disk1', '--yb_num_shards_per_tserver=2', '--ysql_num_shards_per_tserver=2', '--v=0']

  yb-tserver-n3:
    image: yugabytedb/yugabyte:latest
    hostname: yb-tserver-n3
    container_name: yb-tserver-n3
    privileged: true
    ports:
      - 9003:9000 
    entrypoint: ['/home/yugabyte/bin/yb-tserver', '--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100', '--rpc_bind_addresses=yb-tserver-n3:9100', '--memory_limit_hard_bytes=1073741824', '--use_cassandra_authentication=false', '--enable_ysql=true', '--pgsql_proxy_bind_address', 'yb-tserver-n3:5433', '--fs_data_dirs=/mnt/disk0,/mnt/disk1', '--yb_num_shards_per_tserver=2', '--ysql_num_shards_per_tserver=2', '--v=0']

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - yb-master-n1
      - yb-master-n2
      - yb-master-n3
      - yb-tserver-n1
      - yb-tserver-n2
      - yb-tserver-n3
    volumes:
      - $PWD/volumes/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - $PWD/volumes/provisioning:/etc/grafana/provisioning
      - $PWD/volumes/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000
